// src/config.ts

import type { ISoundLicence } from "@/interfaces/soundLicence.interface";

export const soundLicenses: Array<ISoundLicence> = [
  {
    icon: "🎹",
    name: "Draft And Wind.Synth 1(2osc).wav",
    author: "newlocknew",
    url: "https://freesound.org/s/611258/",
    license: "Attribution 4.0",
  },
  {
    icon: "👣",
    name: "Footsteps, Dry Leaves, E.wav",
    author: "InspectorJ",
    url: "https://freesound.org/s/329599/",
    license: "Attribution 4.0",
  },
  {
    icon: "💧",
    name: "water_drip-echo2.wav",
    author: "roscoetoon",
    url: "https://freesound.org/s/27151/",
    license: "Attribution 3.0",
  },
  {
    icon: "💧",
    name: "Ewater_drip-echo.mp3",
    author: "roscoetoon",
    url: "https://freesound.org/s/26921/",
    license: "Attribution 3.0",
  },
  {
    icon: "🔥",
    name: "fire_cracking_01.mp3",
    author: "bokal",
    url: "https://freesound.org/s/559580/",
    license: "Creative Commons 0",
  },
  {
    icon: "🌊",
    name: "Water stream 3",
    author: "Kolezan",
    url: "https://freesound.org/s/132046/",
    license: "Attribution 4.0",
  },
  {
    icon: "🔩",
    name: "Metal warble",
    author: "lori.mortimer",
    url: "https://freesound.org/s/739385/",
    license: "Creative Commons 0",
  },
  {
    icon: "💥",
    name: "quake and break.wav",
    author: "cheetahzbrain",
    url: "https://freesound.org/s/431859/",
    license: "Creative Commons 0",
  },
  {
    icon: "🏞",
    name: "Rolling Rocks 06",
    author: "Uminari",
    url: "https://freesound.org/s/389724/",
    license: "Attribution 4.0",
  },
  {
    icon: "🚪",
    name: "old door screeching.wav",
    author: "Tomlija",
    url: "https://freesound.org/s/98152/",
    license: "Attribution 3.0",
  },
  {
    icon: "🚪",
    name: "Opening a heavy door (and bounding in)",
    author: "pfranzen",
    url: "https://freesound.org/s/262705/",
    license: "Attribution 4.0",
  },
  {
    icon: "🏹",
    name: "Arrow.mp3",
    author: "thecrow_br",
    url: "https://freesound.org/s/574044/",
    license: "Creative Commons 0",
  },
  {
    icon: "💥",
    name: "Spiketrap.wav",
    author: "Deathscyp",
    url: "https://freesound.org/s/443806/",
    license: "Creative Commons 0",
  },
  {
    icon: "🔥",
    name: "Hot Object Quench",
    author: "DJT4NN3R",
    url: "https://freesound.org/s/484158/",
    license: "Attribution NonCommercial 4.0",
  },
  {
    icon: "🐶",
    name: "Distant howling pupper",
    author: "sandboks",
    url: "https://freesound.org/s/503516/",
    license: "Creative Commons 0",
  },
  {
    icon: "🎶",
    name: "Mystery's Embrace",
    author: "Universfield",
    url: "https://freesound.org/s/754505/",
    license: "Attribution 4.0",
  },
  {
    icon: "🎵",
    name: "Viking/Medieval Theme",
    author: "M-Murray",
    url: "https://freesound.org/s/723202/",
    license: "Attribution NonCommercial 4.0",
  },
  {
    icon: "⚔️",
    name: "Epoch of War 5",
    author: "RAME - War Victory Fight Music Loop by RokZRooM",
    url: "https://freesound.org/s/579300/",
    license: "Attribution 4.0",
  },
  {
    icon: "🥊",
    name: "Punching and Uppercut.wav",
    author: "18hiltc",
    url: "https://freesound.org/s/198610/",
    license: "Attribution 4.0",
  },
  {
    icon: "🥊",
    name: "punch.wav",
    author: "Ekokubza123",
    url: "https://freesound.org/s/104183/",
    license: "Creative Commons 0",
  },
  {
    icon: "🥊",
    name: "punches_and_slaps.wav",
    author: "Syna-Max",
    url: "https://freesound.org/s/43586/",
    license: "Attribution NonCommercial 4.0",
  },
  {
    icon: "🍻",
    name: "My Tavern 1.wav",
    author: "ralexpdx",
    url: "https://freesound.org/s/321220/",
    license: "Attribution 4.0",
  },
  {
    icon: "🏰",
    name: "Medieval Tune - Knight's Castle.wav",
    author: "gertraut_hecher",
    url: "https://freesound.org/s/568776/",
    license: "Attribution NonCommercial 4.0",
  },
  {
    icon: "🔔",
    name: "Old Church Bell.wav",
    author: "dsp9000",
    url: "https://freesound.org/s/76405/",
    license: "Creative Commons 0",
  },
  {
    icon: "🎮",
    name: "RPG Maker's Kit 1",
    author: "TheAmbientFort",
    url: "https://theambientfort.itch.io/rpgmakerskit1",
    license: "Attribution NonCommercial 4.0",
  },
  {
    icon: "🦉",
    name: "owl at night",
    author: "opalmirage",
    url: "https://freesound.org/s/666760/",
    license: "Creative Commons 0",
  },
];
