import type { ISound } from "@/interfaces/sound.interface";

export const listOfSound: Array<ISound> = [
  {
    name: "Foot step",
    iconName: "fa-shoe-prints",
    soundName: "footstep.wav",
    shouldRepeat: true,
    soundVolume: 0.5,
  },
  {
    name: "Wind",
    iconName: "fa-wind",
    soundName: "wind.wav",
    shouldRepeat: true,
    soundVolume: 0.5,
  },
  {
    name: "Drips",
    iconName: "fa-droplet",
    soundName: "droplet.wav",
    soundVolume: 0.2,
    shouldRepeat: false,
  },
  {
    soundVolume: 0.2,
    name: "Door Open",
    iconName: "fa-door-open",
    soundName: "262705__pfranzen__opening-a-heavy-door-and-bounding-in.ogg",
    shouldRepeat: false,
  },
  {
    soundVolume: 0.3,
    name: "Fire",
    iconName: "fa-fire",
    soundName: "fire.mp3",
    shouldRepeat: false,
  },
  {
    soundVolume: 0.1,
    name: "Water",
    iconName: "fa-water",
    soundName: "132046__kolezan__water-stream-3.wav",
    shouldRepeat: false,
  },
  {
    soundVolume: 0.1,
    name: "Shimmer",
    iconName: "fa-music",
    soundName: "739385__lorimortimer__metal-warble.wav",
    shouldRepeat: true,
  },
  {
    soundVolume: 0.1,
    name: "Rumble",
    iconName: "fa-hill-rockslide",
    soundName: "431859__cheetahzbrain__quake-and-break.wav",
    shouldRepeat: false,
  },
  {
    soundVolume: 0.5,
    name: "Stone Trap",
    iconName: "fa-skull-crossbones",
    soundName: "389724__uminari__rolling-rocks-06.wav",
    shouldRepeat: false,
  },
  {
    soundVolume: 0.2,
    name: "Screeching",
    iconName: "fa-door-open",
    soundName: "98152__tomlija__old-door-screeching.wav",
    shouldRepeat: false,
  },
  {
    soundVolume: 0.5,
    name: "Arrow Hit",
    iconName: "fa-arrow-right",
    soundName: "574044__thecrow_br__arrow.mp3",
    shouldRepeat: false,
  },
  {
    soundVolume: 0.5,
    name: "Spike Trap",
    iconName: "fa-road-spikes",
    soundName: "443806__deathscyp__spiketrap.wav",
    shouldRepeat: false,
  },
  {
    soundVolume: 0.5,
    name: "Distant wolf",
    iconName: "fa-dog",
    soundName: "503516__sandboks__distant-howling-pupper.wav",
    shouldRepeat: false,
  },
  {
    soundVolume: 0.5,
    name: "Distant Roar",
    iconName: "fa-spaghetti-monster-flying",
    soundName: "Monster roar (Rpg).wav",
    shouldRepeat: false,
  },
  {
    soundVolume: 0.1,
    name: "Punch",
    iconName: "fa-hand-fist",
    soundName: "198610__18hiltc__punching-and-uppercut.wav",
    shouldRepeat: false,
  },
  {
    name: "Theme Intrigue",
    soundVolume: 0.5,
    iconName: "fa-music",
    soundName: "754505__universfield__mysterys-embrace.mp3",
    shouldRepeat: true,
  },
  {
    name: "Theme Action",
    soundVolume: 0.2,
    iconName: "fa-music",
    soundName: "723202__m-murray__vikingmedieval-theme.wav",
    shouldRepeat: true,
  },
  {
    name: "Theme Combat",
    soundVolume: 0.2,
    iconName: "fa-music",
    soundName:
      "579300__rokzroom__epoch-of-war-5-by-rame-war-victory-fight-music-loop.wav",
    shouldRepeat: true,
  },
  {
    soundVolume: 0.5,
    name: "Theme Chill",
    iconName: "fa-music",
    soundName: "Chill RPG theme (RPG).wav",
    shouldRepeat: true,
  },
  {
    soundVolume: 0.5,
    name: "Theme Day",
    iconName: "fa-music",
    soundName: "Ambience Day (Gj).wav",
    shouldRepeat: true,
  },
  {
    soundVolume: 0.3,
    name: "Tavern",
    iconName: "fa-beer-mug-empty",
    soundName: "321220__ralexpdx__my-tavern-1.wav",
    shouldRepeat: true,
  },
  {
    soundVolume: 0.2,
    name: "Church bell",
    iconName: "fa-bell",
    soundName: "76405__dsp9000__old-church-bell.wav",
    shouldRepeat: false,
  },
  {
    soundVolume: 0.1,
    name: "Medieval theme",
    iconName: "fa-music",
    soundName: "568776__gertraut_hecher__medieval-tune-knights-castle.wav",
    shouldRepeat: true,
  },
];
